pid_test_node:
  ros__parameters:
    kp: 1.0
    ki: 0.0
    kd: 0.0

pure_pursuit:
  ros__parameters:
    kp: 1.5
    ki: 0.75
    kd: 0.0
    target_dist: 0.15
    ctrl_period: 0.005

simple_pursuit:
  ros__parameters:
    kp: 2.0
    ki: 0.5
    kd: 0.0
    ctrl_period: 0.005